### ISSUE TITLE
how do you run this app

### ISSUE THREAD

**Issue by baditaflorin** [petervojtek/osm-relation-utils#2]
i have installed ruby , but when i try to run i get htis error

ruby run_webserver.rb
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- active_support/core_ext/hash (LoadError)
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
        from run_webserver.rb:2:in `<main>'
/data/files/florinb/github/osm-relation-utils/src$

**Comment by petervojtek** [comment]
Hi, I updated the readme file to aswer your questions: https://github.com/sk-vpohybe/osm-relation-utils/blob/master/README.md

**Comment by baditaflorin** [comment]
Hi Peter, thenks for the reply.

Do you think that is possible, starting from your script, to generate a
list of the broken relationships, that means, if i have a relation that is
splitted in many parts, to output this info .

Or i better start from zero or search for another example , like this one
http://ra.osmsurround.org/analyzeRelation?relationId=38266&_noCache=on

I liked your script because it can generate bulk "reports"

**Comment by petervojtek** [comment]
hi Badita,

I guess the code is not suitable for your task.
actually I have there an assumtion that the relation cannot be "broken"  (i.e. graph must have only one component) - https://github.com/sk-vpohybe/osm-relation-utils/blob/master/src/journey/journey.rb#L6

you may find this useful:
https://github.com/brianstorti/ruby-graph-algorithms/tree/master/connected_components
